add_newline = false
format = """
$time\
$directory\
$git_branch\
$character
"""

[line_break]
disabled = true

[character]
format = "â¯ "
success_symbol = "â¯(green) "
error_symbol = "â¯(red) "

[time]
disabled = false
format = '[$time]($style) '
style='yellow'
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "+9"

[directory]
disabled = false
format = "[$path]($style)[$read_only]($read_only_style) "
style='blue'
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "~/"

[git_branch]
symbol  =  "ğŸ£ "
disabled = false
format = "[$symbol$branch]($style) "
style='purple'

[git_status]
disabled = true

[hostname]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true
